spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

#    url: jdbc:mysql://localhost:3306/starbucks?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: ssafy
#    password: ssafy
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

#  batch:
#    job.enabled: true # true: ? ??? job ?? ?
#    jdbc.initialize-schema: always

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
#    org.springframework : debug
#    org.springframework.web : debug